### ISSUE TITLE
QOL: Add annotate gem 

### ISSUE THREAD

**Issue by wassson** [caley-io/email-rails#100]
## Expected behavior
`annotate` gem is used to add table annotations to bottom of model files

## Considerations
Can we create a GitHub workflow action that automatically annotates the models for us when we add a new migration? If not, how do we automate?

- [ ] Install [annotate gem](https://github.com/ctran/annotate_models)
- [ ] Add table annotation to the bottom of all model files
- [ ] Document any recurring actions that need to take place every time we add a new migration, and list any automations that we may be able to use to do this for us.

**Comment by sarvaiyanidhi** [comment]
Hi @wassson Can I take up this?

Also as per docs it mentions that annotation on model is done automatically whenever we run db:migrate command

> By default, once you've generated a configuration file, annotate will be executed whenever you run rake db:migrate


Won't it be enough?

**Comment by wassson** [comment]
@sarvaiyanidhi Ah, that makes sense! I couldn't remember so I listed the requirement anyway. We can cross that off then.

**Comment by sarvaiyanidhi** [comment]
Great. will implement and push changes shortly for review.

**Comment by wassson** [comment]
@sarvaiyanidhi thank you! Are you in the discord? Feel free to reach me there as well if I am slow to respond here

**Comment by sarvaiyanidhi** [comment]
Joined Discord :)
