### ISSUE TITLE
👋🏽 Share the Vision! ;)

### ISSUE THREAD

**Issue by son1112** [caley-io/email-rails#80]
### Type of feature
💡 Documentation

### Current behavior
Links to the wiki (ie. https://github.com/caley-io/caley/wiki/Vision in `CONTRIBUTING.md`) re-route to https://github.com/caley-io/caley-rails.

### Suggested solution
It appears that there is either no wiki, not published, public or otherwise. Is there a correct link or is the wiki yet to be published/public/created?

### Additional context
Great project; happy to contribute where I can!

**Comment by jeremyscatigna** [comment]
We are at the moment working on a proper wiki with the entire vision detailed so that it's clearer for everyone that joins the project but in the meantime happy to answer any questions you could have and give more details and insights 😍

**Comment by wassson** [comment]
Yes! This is a great note. Like @jeremyscatigna said, we're working on it haha. But this is where you (and other contributors) should hop into discord and throw out your own ideas into the ideas channel so we can work some of that in as well!

**Comment by son1112** [comment]
> Yes! This is a great note. Like @jeremyscatigna said, we're working on it haha. But this is where you (and other contributors) should hop into discord and throw out your own ideas into the ideas channel so we can work some of that in as well!

Perfect. I am not yet seeing a link to the discord. Would you mind sharing that here? Make sense to put that in CONTRIBUTING.md?

**Comment by wassson** [comment]
> > Yes! This is a great note. Like @jeremyscatigna said, we're working on it haha. But this is where you (and other contributors) should hop into discord and throw out your own ideas into the ideas channel so we can work some of that in as well!
> 
> Perfect. I am not yet seeing a link to the discord. Would you mind sharing that here? Make sense to put that in CONTRIBUTING.md?

Here you go! https://discord.gg/xV8dUPGA
