### ISSUE TITLE
Feature: Replace Pages controller with Emails controller

### ISSUE THREAD

**Issue by wassson** [caley-io/email-rails#83]
## Expected Behavior
Replace the `pages_controller` with a new `emails_controller`, and add a few default views.

- [ ] Create `emails_controller`
- [ ] Remove `pages_controller`
- [ ] Add default `inbox`, `reply_later`, and `all` actions to the `emails_controller`
- [ ] Copy and paste code from `pages/inbox.html.erb` to `emails/inbox.html.erb`
- [ ] Change the `root` route to now render `emails#inbox`
- [ ] Remove `pages` routes, views, tests, and anything else related
- [ ] Scaffold basic `minitest` controller/request tests for the `emails_controller` (don't worry about complete test coverage, but add `TODO`s if needed)

**Comment by nazeefahmadmeer** [comment]
I’ll set up the app locally and complete this one for a start if that’s ok @wassson

**Comment by wassson** [comment]
@nazeefahmadmeer Great! Thank you
