### ISSUE TITLE
Fix: User and Search modal keybinds

### ISSUE THREAD

**Issue by wassson** [caley-io/email-rails#85]
## Expected behavior
The modals should open independently, and close other modals so that only one can be open at a time.

# Note
Please reach out to @wassson with any questions. This can get confusing without mocks. 

1. User modal
- [ ] Opens and closes with the `u` key
- [ ] Opens and closes when clicking the user profile picture in the floating nav at the bottom
- [ ] Closes when clicking elsewhere on the screen
- [ ] Closes all other open modals other than "user settings"
- [ ] Opening the modal stops the 'up' and 'down' arrow keys from navigating between email list items on the page and instead navigates between list items in the modal
- [ ] Cannot be opened when the "user settings" modal is open

2. Search modal
- [ ] Opens with the `/` key (we don't want it to close with '/' so the user can use that key in searches)
- [ ] Opens and closes when clicking the user profile picture in the floating nav at the bottom
- [ ] Closes when clicking elsewhere on the screen
- [ ] Closes all other open modals other than "user settings"
- [ ] Opening the modal stops the 'up' and 'down' arrow keys from navigating between email list items on the page and instead navigates between list items in the modal
- [ ] Cannot be opened when the "user settings" modal is open

**Comment by Etx17** [comment]
Hey! i'll take a loot into this one.

**Comment by wassson** [comment]
@Etx17 awesome thank you!
